import Head from 'next/head'
import Cards from '../components/Cards'

export default function Home() {
  return (
    <div className='dark:bg-black h-full'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Cards />
    </div>
  )
}