import Head from 'next/head'
import Cards from '../components/Cards'
import { getXataClient } from '../utils/xata'

export default function Home({ cards, error }) {
  return (
    <div className='dark:bg-black h-full'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <Cards cards={cards} error={error} />
    </div>
  )
}

export async function getServerSideProps(context) {
  const xata = getXataClient();
  try {
    const cards = await xata.db.Cards.select(["*", "user.*"]).getAll();
    return {
      props: { cards },
    }
  } catch (error) {
    return {
      props: { cards: null, error: "Something went wrong." }
    }
  }

}